/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CampaignsImport } from './routes/campaigns'
import { Route as AccountImport } from './routes/account'
import { Route as IndexImport } from './routes/index'
import { Route as CampaignsCreateImport } from './routes/campaigns_.create'
import { Route as CampaignNotesImport } from './routes/$campaign.notes'

// Create/Update Routes

const CampaignsRoute = CampaignsImport.update({
  path: '/campaigns',
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CampaignsCreateRoute = CampaignsCreateImport.update({
  path: '/campaigns/create',
  getParentRoute: () => rootRoute,
} as any)

const CampaignNotesRoute = CampaignNotesImport.update({
  path: '/$campaign/notes',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsImport
      parentRoute: typeof rootRoute
    }
    '/$campaign/notes': {
      id: '/$campaign/notes'
      path: '/$campaign/notes'
      fullPath: '/$campaign/notes'
      preLoaderRoute: typeof CampaignNotesImport
      parentRoute: typeof rootRoute
    }
    '/campaigns/create': {
      id: '/campaigns/create'
      path: '/campaigns/create'
      fullPath: '/campaigns/create'
      preLoaderRoute: typeof CampaignsCreateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/campaigns': typeof CampaignsRoute
  '/$campaign/notes': typeof CampaignNotesRoute
  '/campaigns/create': typeof CampaignsCreateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/campaigns': typeof CampaignsRoute
  '/$campaign/notes': typeof CampaignNotesRoute
  '/campaigns/create': typeof CampaignsCreateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/campaigns': typeof CampaignsRoute
  '/$campaign/notes': typeof CampaignNotesRoute
  '/campaigns/create': typeof CampaignsCreateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/campaigns'
    | '/$campaign/notes'
    | '/campaigns/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/campaigns' | '/$campaign/notes' | '/campaigns/create'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/campaigns'
    | '/$campaign/notes'
    | '/campaigns/create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CampaignsRoute: typeof CampaignsRoute
  CampaignNotesRoute: typeof CampaignNotesRoute
  CampaignsCreateRoute: typeof CampaignsCreateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CampaignsRoute: CampaignsRoute,
  CampaignNotesRoute: CampaignNotesRoute,
  CampaignsCreateRoute: CampaignsCreateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/account",
        "/campaigns",
        "/$campaign/notes",
        "/campaigns/create"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/account": {
      "filePath": "account.tsx"
    },
    "/campaigns": {
      "filePath": "campaigns.tsx"
    },
    "/$campaign/notes": {
      "filePath": "$campaign.notes.tsx"
    },
    "/campaigns/create": {
      "filePath": "campaigns_.create.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
