/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotesImport } from './routes/notes'
import { Route as AccountImport } from './routes/account'
import { Route as NoteImport } from './routes/$note'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NotesRoute = NotesImport.update({
  path: '/notes',
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const NoteRoute = NoteImport.update({
  path: '/$note',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$note': {
      id: '/$note'
      path: '/$note'
      fullPath: '/$note'
      preLoaderRoute: typeof NoteImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$note': typeof NoteRoute
  '/account': typeof AccountRoute
  '/notes': typeof NotesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$note': typeof NoteRoute
  '/account': typeof AccountRoute
  '/notes': typeof NotesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$note': typeof NoteRoute
  '/account': typeof AccountRoute
  '/notes': typeof NotesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$note' | '/account' | '/notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$note' | '/account' | '/notes'
  id: '__root__' | '/' | '/$note' | '/account' | '/notes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoteRoute: typeof NoteRoute
  AccountRoute: typeof AccountRoute
  NotesRoute: typeof NotesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoteRoute: NoteRoute,
  AccountRoute: AccountRoute,
  NotesRoute: NotesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$note",
        "/account",
        "/notes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$note": {
      "filePath": "$note.tsx"
    },
    "/account": {
      "filePath": "account.tsx"
    },
    "/notes": {
      "filePath": "notes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
